[project]
name = "aiyogasequencegenerator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=1.23.0",
    "scikit-learn>=1.2.0",
    "sentence-transformers>=2.2.0",
]
